### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [mdaffin/loopdev#3]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Looks like this is blocked by https://github.com/docopt/docopt.rs/issues/128.

**Comment by mdaffin** [comment]
Docopts is only required for the losetup bin. I have started to use [clap](https://crates.io/crates/clap) instead for newer projects (which does not depend on rustc-serialize) so I will look at converting this project to use it as well.

**Comment by mdaffin** [comment]
I have moved the losetup bin into its own sub crate so that its dependencies do not affect the library at all and converted it to use clap so that rustc-serialize is not used at all anymore. A new version has been published to crates.io (0.1.2) with these changes.
