### ISSUE TITLE
Release 0.2.2 on crate.io

### ISSUE THREAD

**Issue by flxo** [mdaffin/loopdev#37]
@mdaffin Would you mind releasing v0.2.2 on crates io?

The new features are:

* Build and run on Android
* Add `LoopDevice::major` and `LoopDevice::minor`
* Add `readonly`, `autoclear` and `direct io` flags
* Use bindgen instead of hard coded constants and types

Thanks!

**Comment by mdaffin** [comment]
This has _finally_ been released. Let me know if there are any issues.
