### ISSUE TITLE
Unable to `cargo build` on OSX

### ISSUE THREAD

**Issue by RRethy** [mdaffin/loopdev#60]
Running `cargo build` produces an error, is there some setup step I'm missing or can this crate not be built on OSX?

Error:

```
$ cargo build 
   Compiling loopdev v0.5.0 (/Users/rethy/rust/loopdev)
error: failed to run custom build command for `loopdev v0.5.0 (/Users/rethy/rust/loopdev)`

Caused by:
  process didn't exit successfully: `/Users/rethy/rust/loopdev/target/debug/build/loopdev-7d51fc8cf50a1a5a/build-script-build` (exit status: 101)
  --- stderr
  /Users/rethy/rust/loopdev/wrapper.h:1:10: fatal error: 'linux/loop.h' file not found
  thread 'main' panicked at 'Could not generate bindings: ClangDiagnostic("/Users/rethy/rust/loopdev/wrapper.h:1:10: fatal error: 'linux/loop.h' file not found\n")', build.rs:11:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

System info:

```
OS: macOS 11.4 20F71 x86_64 
Host: MacBookPro12,1 
Kernel: 20.5.0 
CPU: Intel i7-5557U (4) @ 3.10GHz 
GPU: Intel Iris Graphics 6100 
```

**Comment by mdaffin** [comment]
This crate is basically an abstraction over the loopback kernel interface for Linux. It was never designed for OSX - I am not even sure it has the same syscalls? I don't have the equipment or time to really support other OSs, but would welcome a PR to add such support if the other systems share a similar kernel interface.

Though it may also be better to keep this Linux focused and create other crates that are focused on other OSs with a wrapper crate that takes care of the differences between them if there are any? I don't know enough about OSX to really say which way is better.

But as it stands I cannot support OSX without additional help.
