### ISSUE TITLE
Release 0.5.0?

### ISSUE THREAD

**Issue by mulkieran** [mdaffin/loopdev#62]
This would be a bit of a help for Fedora packaging. We're accumulating patches just a bit, but it's rather frowned on in Fedora to pull from anything other than an actual release.

**Comment by flxo** [comment]
I'm also at the point where I would like a 0.5.0 release with the `add` feature. Thanks @mdaffin

**Comment by mulkieran** [comment]
Note though, that https://github.com/mdaffin/loopdev/pull/63 would be important to us. Right now, the current release of loopdev is failing to build on various releases and rust toolchain versions, due to bindgen failures.

**Comment by flxo** [comment]
@mdaffin Anything I can support you with?

**Comment by flxo** [comment]
@mdaffin This is a gentle ping.

**Comment by eatradish** [comment]
`loopdev 0.4.0` is broken by llvm 16:

```bash
$ cargo check
   Compiling loopdev v0.4.0
error: failed to run custom build command for `loopdev v0.4.0`

Caused by:
  process didn't exit successfully: `/home/saki/aoscdk-rs/target/debug/build/loopdev-0fd479182e7ace07/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at '"enum_(unnamed_at_/usr/include/linux/loop_h_16_1)" is not a valid Ident', /home/saki/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.66/src/fallback.rs:774:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

Hopefully loopdev 0.5.0 will be released on crates.io as soon as possible to address this issue with the new bindgen

**Comment by surajssd** [comment]
We also faced this issue: https://github.com/confidential-containers/cloud-api-adaptor/issues/1358

**Comment by erikh** [comment]
@mdaffin Just pointing out this issue is 6 months old. On linux 6.1.60, loopdev 0.4.0 refuses to compile, yet the master branch here compiles without a hitch. Please release this.

**Comment by erikh** [comment]
To deal with this problem in the most constructive way possible that allows me to compile my code, I have released `loopdev-erikh` 0.5.0 which does work with my own stack. It is available on crates.io and is hosted at https://github.com/erikh/loopdev. I have added my name to the copyright as well as the authors list and ensured all tests pass on linux 6.x. I am more than happy to field questions and patches from other contributors that depend on this library. As I run into problems, or get patches and bug reports I can field I will continue maintenance to ensure the stability of the library for all users.

If you are interested in releasing and maintaining your software, kindly notify me in this ticket or on my fork and I will happily discontinue maintaining my fork. I don't want to maintain this software, I unfortunately need to.

**Comment by mulkieran** [comment]
@mdaffin @erikh

The Stratis team realized that we would likely be better off maintaining our own version: https://github.com/stratis-storage/loopdev-3 . It is called loopdev-3, because, apparently, it will be the third fork. We were able to release it in Fedora: https://src.fedoraproject.org/rpms/rust-loopdev-3. And we will probably be able to accept some PRs, though not at a very rapid pace.

We want to thank @mdaffin for all the hard work that went into this library which has always been deeply appreciated. 

We want to thank @erikh for making us realize that forking was probably the best choice. Perhaps our fork will work out for you also.

**Comment by mulkieran** [comment]
And I'll go ahead and close, with this: https://github.com/stratis-storage/loopdev-3/releases/tag/loopdev-3-v0.5.0 .

**Comment by erikh** [comment]
SGTM, honestly, I have very limited needs, I just do need it to compile cleanly. :)

**Comment by erikh** [comment]
fwiw, I amended the README and description of erikh/loopdev to link to the new repository. I also flagged erikh/loopdev read-only.

I went to go post this as an issue; I would hope that new repository could be the resting ground for issues as well as code. Thanks.

-Erik
